#!/usr/bin/env python3
"""
zTheme Build Script - Layered CSS Architecture
Resolves @imports recursively across all layers and concatenates into dist/ztheme.css

Layer order (LFS-style — each layer composes from layers below):
  L0_Reset       → pure normalization + font loading (no opinions)
  L1_Foundation  → variables (tokens) + base element styles
  L2_Layout      → containers, grid system
"""
import shutil
from pathlib import Path

# Each entry is an @import facade; all @imports within are resolved recursively.
# Paths are relative to src/css/ (entry dir), so ../ steps up to src/
CSS_LAYERS = [
    '../L0_Reset/zTheme_L0.css',
    '../L1_Foundation/zTheme_L1.css',
    '../L2_Layout/zTheme_L2.css',
    '../L3_Basic/zTheme_L3.css',

]


def resolve_css_imports(file_path, processed_files=None):
    """Recursively inline all @import statements in a CSS file."""
    if processed_files is None:
        processed_files = set()

    abs_path = file_path.resolve()
    if abs_path in processed_files:
        return ""
    processed_files.add(abs_path)

    if not file_path.exists():
        return f"/* Warning: {file_path} not found */\n"

    content = file_path.read_text(encoding='utf-8')
    result = []

    for line in content.split('\n'):
        stripped = line.strip()
        if stripped.startswith('@import'):
            if "'" in stripped:
                import_path = stripped.split("'")[1]
            elif '"' in stripped:
                import_path = stripped.split('"')[1]
            else:
                result.append(line)
                continue

            imported_file = (file_path.parent / import_path).resolve()
            result.append(f"\n/* ── {import_path} ── */")
            result.append(resolve_css_imports(Path(imported_file), processed_files))
        else:
            result.append(line)

    return '\n'.join(result)


def build_ztheme():
    base_dir = Path(__file__).parent
    src_css_dir = base_dir / 'src' / 'css'
    dist_dir = base_dir / 'dist'
    output_file = dist_dir / 'ztheme.css'
    fonts_src = base_dir / 'src' / 'L0_Reset' / 'fonts'
    fonts_dist = dist_dir / 'fonts'

    dist_dir.mkdir(exist_ok=True)

    print("Building zTheme CSS...")
    print(f"  Output: {output_file}\n")

    if fonts_src.exists():
        if fonts_dist.exists():
            shutil.rmtree(fonts_dist)
        shutil.copytree(fonts_src, fonts_dist)
        print(f"Copied fonts → {fonts_dist}\n")

    with open(output_file, 'w', encoding='utf-8') as outfile:
        outfile.write(
            '/**\n'
            ' * zTheme — Complete CSS Framework (Compiled)\n'
            ' * DO NOT EDIT — generated by build.py from src/\n'
            ' */\n\n'
        )

        for layer_path in CSS_LAYERS:
            source_path = (src_css_dir / layer_path).resolve()

            if not source_path.exists():
                print(f"  SKIP  {layer_path} (not found)")
                continue

            print(f"  OK    {layer_path}")
            outfile.write(f'\n/* {"═" * 60}\n   {layer_path}\n   {"═" * 60} */\n')

            content = resolve_css_imports(source_path)

            # Normalize font paths from any depth → dist-relative fonts/
            content = content.replace("url('../fonts/", "url('fonts/")
            content = content.replace("url('../L0_Reset/fonts/", "url('fonts/")
            content = content.replace("url('../L1_Foundation/fonts/", "url('fonts/")

            outfile.write(content)
            outfile.write('\n')

    size_kb = output_file.stat().st_size / 1024
    print(f"\nBuild complete — {size_kb:.1f} KB → {output_file}")


if __name__ == '__main__':
    build_ztheme()
